### ISSUE TITLE
Readings are Off-By-One when Compared to All other Studio Courses (product management, startup ideas)

### ISSUE THREAD

**Issue by gnauhnoj** [cornelltech/startup-studio#1]
Hi,

I'm not sure if this is just me, but I just realized that I did the wrong readings for this past class because (I think) they're intended to be listed under "homework" -- despite using the same header. Instead, I read about pitch decks. 

This comes in contrast to the other studio courses (specifically [Product Management](https://github.com/cornelltech/product-management/wiki#session-2-product--data-attack-of-the-data) and [Startup Ideas](https://github.com/cornelltech/startup-ideas/wiki)) where the "Readings" header corresponds to the readings for that week. [Startup Ideas](https://github.com/cornelltech/company-challenges/wiki/Syllabus#session-2-unpack) took the approach of specifically listing "Pre-Readings."

Overall, I think based on this precedent (at least for this year), the wiki for this course is really confusing. At the end of the day it was my mistake for not reading the topics for the day to map this time shift over, but it was slightly annoying to realize this post in-class assignment. 

I propose specifying that the readings are meant to be a sub-section of homework, or moving the readings into the next class section and using the "Pre-Readings" header. If it makes it easier, I'd be happy to make this change and submit a PR.

Thanks,

**Comment by rohit-jain** [comment]
+1

**Comment by jingdai2014** [comment]
+1! i run into the same issue this week...

**Comment by brunnoattorre** [comment]
+1

**Comment by jcornellnyc** [comment]
Readings are listed under homework for Startup Studio. The wiki has been updated to be even more clear about this! Let me know if it still isn't clear what needs to be read before each class.
